spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create # DB 스키마 설정이 완료되면 validate로 반드시 변경
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        highlight_sql: true
      default_batch_fetch_size: 100